"""
Django settings for cafe_project project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = "django-insecure-nk0r8732s=&-+n9hhuzw25lxx153n@ev5)1s4syv+m+7@^*7h6"
DEBUG = True
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "cafe",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]



TWITTER_CLIENT_ID = '3basPcmLAION9SNmRN26ZsvGj'
TWITTER_CLIENT_SECRET = 'sVB3cofRPc6CRydqbiO1pTIQW6fm2sSQupJsph3gJddYrapf06'
TWITTER_CALLBACK_URL = 'http://127.0.0.1:8000/twitter/callback/'



ROOT_URLCONF = "cafe_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cafe_project.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",  # Path to the SQLite database file
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default session engine (db-based)
SESSION_COOKIE_SECURE = False  # Set to True for production (if using https)
SESSION_COOKIE_HTTPONLY = True


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

LOGIN_URL = '/login/'  # Ensure this matches the login URL in your urlpatterns
LOGIN_REDIRECT_URL = '/'  # Redirect users to the home page after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect users to the login page after logout


CORS_ALLOW_ALL_ORIGINS=True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")  # For deployment

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Store media files

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
